#!/usr/bin/env python

Import('env')
Import('env_modules')

env_module = env_modules.Clone()

env_module.Append(
	CPPFLAGS="-Imodules/NativeDialogs/NativeDialogs",
	CXXFLAGS="-std=c++14"
)
env_module.add_source_files(env.modules_sources,"NativeDialogs/*.cpp")
env_module.add_source_files(env.modules_sources,"NativeDialogs/gtk/*.cpp")
env_module.add_source_files(env.modules_sources,"*.cpp")

if env["platform"] == "x11":
	env_module.ParseConfig('pkg-config --cflags gtk+-3.0')
	env.ParseConfig('pkg-config --libs gtk+-3.0')
